name: lint-workflow-runners

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-workflow-runners:
    uses: ./.github/workflows/lint_workflow_runners.yaml
    with:
      runner: ${{ fromJSON(vars.RUNNER_PROFILES)[vars.RUNNER_PROFILE].default }}
